### ISSUE TITLE
options.quality is unsupported for the png screenshots

### ISSUE THREAD

**Issue by paulo-santos-ideahub** [morteza-fsh/puppeteer-full-page-screenshot#19]
I don't know what I'm doing wrong.
```
options.quality is unsupported for the png screenshots
at Object.assert (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/assert.js:26:15)
at Page.screenshot (/usr/src/app/node_modules/puppeteer/lib/cjs/puppeteer/common/Page.js:1094:25)
at Object.fullPageScreenshot [as default] (/usr/src/app/node_modules/puppeteer-full-page-screenshot/lib/index.js:49:30)
```

Here's the relevant section:
```
//page goto happens here:
let pathName = `/tmp/converted-${Date.now()}.jpg`;
console.log(pathName);
await fps.default(page,{
  path: pathName
}).then(//do something);
//snip
```

`console.log` confirms that it's indeed being passed as a jpg. 
If it matters, I'm running this project in Docker, using `buildkite/puppeteer:10.0.0` as the base image.

**Comment by morteza-fsh** [comment]
This issue has been fixed, please update the package and try again.
