### ISSUE TITLE
Unexpected end of input     at module.exports.ChunkStream._end

### ISSUE THREAD

**Issue by mrtrandinhvn** [morteza-fsh/puppeteer-full-page-screenshot#21]
### Issue
There's an edge case in `fullPageScreenshot` method. When `extraPixels` = `0`, pngjs will crash when you try to crop last image in this line since the output image will have `height = 0`.
```
const cropped = await _jimp.default.read(images.pop()).then(image => image.crop(0, viewport.height - extraPixels, viewport.width, extraPixels)).then(image => image.getBufferAsync(_jimp.default.AUTO));
```

I believe a simple `if` statement can solve that:
```
if (extraPixels > 0) {
    const cropped = await _jimp.default.read(images.pop()).then(image => image.crop(0, viewport.height - extraPixels, viewport.width, extraPixels)).then(image => image.getBufferAsync(_jimp.default.AUTO));
    images.push(cropped);
}
```

### Error log
> Uncaught exception: Unexpected end of input Error: Unexpected end of input
    at module.exports.ChunkStream._end (C:\Works\ericssondotcom-at\backstop\node_modules\merge-img\node_modules\pngjs\lib\chunkstream.js:101:9)
    at module.exports.ChunkStream.end (C:\Works\ericssondotcom-at\backstop\node_modules\merge-img\node_modules\pngjs\lib\chunkstream.js:86:10)
    at Inflate.emit (node:events:526:28)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
C:\Works\ericssondotcom-at\backstop\node_modules\backstopjs\cli\index.js:46
      throw err;
      ^
Error: Unexpected end of input
    at module.exports.ChunkStream._end (C:\Works\ericssondotcom-at\backstop\node_modules\merge-img\node_modules\pngjs\lib\chunkstream.js:101:9)
    at module.exports.ChunkStream.end (C:\Works\ericssondotcom-at\backstop\node_modules\merge-img\node_modules\pngjs\lib\chunkstream.js:86:10)
    at Inflate.emit (node:events:526:28)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Emitted 'error' event on  instance at:
    at module.exports.ChunkStream._end (C:\Works\ericssondotcom-at\backstop\node_modules\merge-img\node_modules\pngjs\lib\chunkstream.js:100:12)
    at module.exports.ChunkStream.end (C:\Works\ericssondotcom-at\backstop\node_modules\merge-img\node_modules\pngjs\lib\chunkstream.js:86:10)
    [... lines matching original stack trace ...]
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

![image](https://user-images.githubusercontent.com/11169633/164890547-11255b68-4f4a-46e1-aa34-0d506a985da0.png)

**Comment by morteza-fsh** [comment]
Thanks for reporting this issue. I'll add a fix shortly, or any PR for this issue is appreciated.

**Comment by mrtrandinhvn** [comment]
@morteza-fsh Thanks for quick response! I created PR #22  for this issue.

**Comment by morteza-fsh** [comment]
@mrtrandinhvn Great 👍 Thanks

**Comment by mrtrandinhvn** [comment]
@morteza-fsh may I know when will the fix be released to npm?
