### ISSUE TITLE
No matching constructor overloading was found. Please see the docs for how to call the Jimp constructor.

### ISSUE THREAD

**Issue by timlg07** [morteza-fsh/puppeteer-full-page-screenshot#24]

**Comment by viperet** [comment]
I have the same problem:

```
/workspace/node_modules/@jimp/utils/src/index.js:15
    error = new Error(error);
            ^
Error: No matching constructor overloading was found. Please see the docs for how to call the Jimp constructor.
    at Jimp.throwError (/workspace/node_modules/@jimp/utils/src/index.js:15:13)
    at Jimp (/workspace/node_modules/@jimp/core/src/index.js:380:27)
    at _construct (/workspace/node_modules/@babel/runtime/helpers/construct.js:4:60)
    at <anonymous> (/workspace/node_modules/@jimp/core/src/index.js:874:5)
    at new Promise (<anonymous>)
    at Function.Jimp.read (/workspace/node_modules/@jimp/core/src/index.js:872:10)
    at fullPageScreenshot (/workspace/node_modules/puppeteer-full-page-screenshot/src/index.js:54:31)
```

**Comment by timlg07** [comment]
I would love to fix it myself, but I can't get this repository here running 🙈
